#!/usr/bin/env python
import rospy

from hmi_telegram.telegram_autocompletions import TelegramAutocompletions

if __name__ == '__main__':
    rospy.init_node('telegram_options')
    TelegramAutocompletions(rospy.get_name())
    rospy.spin()
